name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-18.04
    steps:
    # Checkout the current branch
    - uses: actions/checkout@v2
    - name: make build dir
      run: mkdir build
    - name: cmake
      run: cmake ..
      working-directory: ./build
    - name: make
      run: make -j 2
      working-directory: ./build
  build-windows:
    runs-on: windows-2019
    steps:
    # Checkout the current branch
    - uses: actions/checkout@v2
    - name: make build dir
      run: mkdir build
    - name: cmake
      run: cmake ..
      working-directory: ./build
    - name: nmake
      run: nmake -j 2
      working-directory: ./build
  build-macos:
    runs-on: macos-10.15
    steps:
    # Checkout the current branch
    - uses: actions/checkout@v2
    - name: make build dir
      run: mkdir build
    - name: cmake
      run: cmake ..
      working-directory: ./build
    - name: make
      run: make -j 2
      working-directory: ./build
  